apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote
    tier: frontend
    autor: rolando  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      tier: frontend
      autor: rolando
  template:
    metadata:
      labels:
        app: vote
        tier: frontend
        autor: rolando  
    spec:
      containers:
      - name: vote
        image: rolandop/vote:v1
        ports:
        - containerPort: 80
